# Generated by Django 3.2.7 on 2021-09-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Employee',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ContractEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.employee')),
                ('payperhour', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ContractEmployee',
                'db_table': 'contractemployee',
            },
            bases=('app1.employee',),
        ),
        migrations.CreateModel(
            name='RegularEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.employee')),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'RegularEmployee',
                'db_table': 'regularemployee',
            },
            bases=('app1.employee',),
        ),
    ]
