# Generated by Django 3.2.7 on 2021-10-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('author', models.CharField(max_length=200, null=True)),
                ('isbn', models.CharField(max_length=20)),
                ('storename', models.CharField(max_length=20)),
            ],
        ),
    ]
