# Generated by Django 3.2.6 on 2021-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('mobileNumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
