# Generated by Django 3.2.7 on 2021-09-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('nop', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
